### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by dornie** [kmontag/modeStep#2]
i finally manage to make modestep poping up in the surface control drop down list.
i activated the ports etc but the softstep don't jump into transport mode as expected, it just stay into is normal set.
try every port i could and various config but didn't manage to enter into modetstep mode
i'm under window 11 and live 12

**Comment by kmontag** [comment]
Could you upload your Live log output? I believe it's at `\Users\[username]\AppData\Roaming\Ableton\Live x.x.x\Preferences\Log.txt` on Win.

Also, make sure your SoftStep firmware is up to date (v2.0.3) and try again with the changes that I just pushed. There were some issues with newer firmware versions that should now be fixed.

**Comment by dornie** [comment]
[Log.txt](https://github.com/kmontag/modeStep/files/15286431/Log.txt)
 here's my log

**Comment by dornie** [comment]
[Log.txt](https://github.com/kmontag/modeStep/files/15286477/Log.txt)
 hop updated log

**Comment by dornie** [comment]
[Log.txt](https://github.com/kmontag/modeStep/files/15286767/Log.txt)
new log

**Comment by dornie** [comment]
[Log.txt](https://github.com/kmontag/modeStep/files/15286839/Log.txt)

**Comment by dornie** [comment]
[Log.txt](https://github.com/kmontag/modeStep/files/15286895/Log.txt)

**Comment by kmontag** [comment]
Debugged elsewhere, will update the README with some troubleshooting stuff 👍
