### ISSUE TITLE
tap tempo send info with foot on AND off

### ISSUE THREAD

**Issue by schlam-schlam** [kmontag/modeStep#6]
Hello

Thank you a lot for your control surface. It's really useful and powerful, but after some test I found an issue with the tap tempo.
I don"t manage to use it since, on my unit, the button send (not each time) information to Live on Foot On AND on foot OFF.
So it's almost impossible to tap a tempo accuretly.

Also, is there a way to have a mode that send a choosen MIdi information like a note or a CC as the regular editor allows.
It should very useful to have that. I know well M4L but really not at all pyhton, I tried to midified the script without any success.

For the tap tempo button behaviour, how can I set the button to only send info when it's press once ? the corresponding button maybe should be configurated as "fast trig".

Thank you again for your script

Julien

**Comment by kmontag** [comment]
Hm, it sounds like one of the SoftStep's hosted-mode CCs might be MIDI-mapped to Tap Tempo in your set.

Can you try disabling the `Remote` checkbox for the modeStep input in your Live settings, and then just using the standard modeStep Tap Tempo button (button 9 in Transport mode)? That should hopefully have the correct behavior.

To explain what's (likely) happening here: modeStep puts the SoftStep into hosted mode to get data from all pressure sensors, which means that the controller sends pressure values (using hardcoded CC numbers) whenever the pressure on any sensor changes. If `Remote` is enabled and any of those CCs are also MIDI-mapped in your Live set, 💥 may ensue.

The README's advice was a bit outdated on this, I've just updated it.

-----

> Also, is there a way to have a mode that send a choosen MIdi information like a note or a CC as the regular editor allows.
It should very useful to have that. I know well M4L but really not at all pyhton, I tried to midified the script without any success.

You can set up modeStep to load your existing [standalone presets](https://github.com/kmontag/modeStep?tab=readme-ov-file#standalone-presets), i.e. switch in/out of hosted mode and send standard PC messages to load your presets.

As described in that README section, if you want to do this, you'd also need to re-enable the input's `Remote` checkbox, and make sure that your set's MIDI mappings follow the guidelines to avoid conflicts with the hosted-mode CCs.

Let me know if you have any questions or further issues.

**Comment by schlam-schlam** [comment]
Hello Kevin,
thank you to answer me.
I reset the sofstep with the editor to default and nothing is mapped in
Live to the tap tempo.
Even with a new live.set the tap tempo is erratic. I can see thatalmost
each time, the tap tempo button blink on note on and note off, making
impossible to use this function..
Do you have an idea of another cullprit ?

Thank you again for this wonderful script

Have a nice day !

Julien

Le mer. 4 déc. 2024 à 00:47, Kevin Montag ***@***.***> a
écrit :

**Comment by kmontag** [comment]
Can you let me know what happens if you follow these steps exactly?

1. In your Live settings under Link, Tempo, & MIDI, make sure that the `modeStep` control surface is mapped to the SoftStep input and output
2. Open a new Live set, and confirm that it has no MIDI mappings at all
3. Confirm that `Trns` appears on the SoftStep's display
4. Tap button 9 on the SoftStep to tap the tempo

I'm also curious, does the other modeStep functionality work as expected for you? For example if you press button 3 while the `Trns` mode is active, does it toggle Play/Stop?

**Comment by kmontag** [comment]
also, please make sure the SoftStep editor is closed before you open the Live set.

**Comment by schlam-schlam** [comment]
Hello Kevin,

sorry for the late reply.
after investigations it was a max msp patch running on background which was
the culprit, the tap tempo is now working properly.
But I don"t manage to add a "user.py" file with your example :

# user.pyfrom .control_surface.configuration import Configuration
configuration = new Configuration(
  # Map Mode Select button 5 to setlist programs 1/2 on short/long press.
  override_modes={5: ("standalone_1", "standalone_2")}
)


Maybe I am not doing stuff correctly.


sofstep editor is closed. 2 presets are in the standalone setlist with CC
80 channel 1/ Foot On on button 0

If I create a file "user.py" in /user library/Remote scripte/modestep and
only paste in it the code above
-->the control surface is not working at all, even after restratuing Live.
If I delete this file and restart Live the control surface is working
properly again.

I precise I kinow well maxmsp/m4L but not at all pyhton or others langages.
I try to put this user.py in the folder /user library/Remote
scripte/modeste/control_surface, the result is the same.


SoftSTep firmware is 2.0.4
Live 12.1.5b4
modestep 0.0.4
SOftstep editor 3..03

Do you have an idea of what I am doing wrong ?

thank you again, the new readme helps me more than the precedent one.

have a nice day

Julien

Le sam. 7 déc. 2024 à 23:22, Kevin Montag ***@***.***> a
écrit :

**Comment by schlam-schlam** [comment]
edit : if I create the user.py file in folder modstep/control_surface,

 after restrating Live the Control surface is working but pressing 0 then 5
still leads to the CLIP mode.

        if the file is created in the root folder 'modstep/' ,then, after a
restart, the control surface doesn't work.

**Comment by kmontag** [comment]
Glad it's working!

There was a typo in the example `user.py` - try it without the `new`, see https://github.com/kmontag/modeStep/commit/cd1cfa4ea8a53eca10770ea89e89c208ec979177.  The file should be in the root `modeStep` directory.

Also, make sure the `from .control_surface.configuration import Configuration` is on a separate line from the comment at the top of the file - maybe that's just a formatting issue in your comment but just making sure.

For reference, things like syntax or runtime errors should show up in Live's log file (see the log file section [here](https://help.ableton.com/hc/en-us/articles/209071629-Where-to-find-Crash-Reports)).

Please let me know if that fixes the `user.py` issue.

**Comment by kmontag** [comment]
Closing as it appears the original issue is solved. Feel free to open a new issue or comment here if you run into further issues with the `user.py` configuration.

**Comment by schlam-schlam** [comment]
Hello Kevin

I had some issue with the softstep and after a great discussion with
support they gave me the next beta of the firmware and the editor, I
thought you could be interested to look at that, It fixs a bug i had with
the smooth parameter that was not working in Live -and maybe in another daw)

Maybe you already have those files.

Cheers

Julien

SoftStep Editor Beta 3.0.5A

Windows:
https://www.dropbox.com/scl/fi/jbvqfzqxs173tyt6piakr/SoftStep
-Editors-v3.0.5.A-Windows-Installer.exe?rlkey=004ga24hg7fkpuyp3ww3x3rpk&dl=0

Macos:
https://www.dropbox.com/scl/fi/czz1np7538f0ff4ax7h5z/SoftStep
-Mac-v3.0.5A.dmg?rlkey=fukz1yu5i0i2g10b4ilu8qoxx&dl=0

Changelog:
https://www.dropbox.com/scl/fi/ejomphnl1c4j9mdabaa88/CHANGELOG.md?rlkey=c08z301v3onuoyqj6m8chlo3y&dl=0


Le ven. 20 déc. 2024 à 00:58, Kevin Montag ***@***.***> a
écrit :

**Comment by kmontag** [comment]
thanks, hadn't seen those updates but good to know!
